package:
  name: reqrep
  version: "{{ load_setup_py_data().version }}"

build:
  noarch: python


source:
  path: ..

requirements:
  build:
    - python 
    - setuptools

  run:
    - python
    - rich
    - pyzmq

test:
  source_files:
    - tests/
  imports:
    - reqrep
  commands:
    - python -m pytest
  requires:
    - pytest


about:
  home: https://github.com/slsdetectorgroup/reqrep
  license: MIT
  license_family: MIT
  summary: Simple remote procedure call using ZMQ REQ/REP
