name: build-conda-package
on: [push, pull_request]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      # Builds the package using the standard configuration
      - uses: cascode-labs/build-conda-action/action.yml@v0
